# Generated by Django 2.0.3 on 2018-03-07 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_usersetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('score', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='usersetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
