# Generated by Django 2.0.3 on 2018-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20180307_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorehistory',
            name='score_delta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
