# Generated by Django 2.0.3 on 2018-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_userscorehistory_score_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscorehistory',
            name='message',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
