# Generated by Django 2.0.3 on 2018-03-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_userscorehistory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytask',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.UserSetup'),
        ),
    ]
