# Generated by Django 2.0.3 on 2018-03-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_companytask_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytask',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companytask',
            name='penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytask',
            name='regular',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyrule',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='companytask',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.UserSetup'),
        ),
        migrations.AlterField(
            model_name='companytask',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscorehistory',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersetup',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
