# Generated by Django 2.0.3 on 2018-04-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_auto_20180414_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iospush',
            old_name='deviceId',
            new_name='device_id',
        ),
    ]
